easy_admin:
    # On définit le nom de l'interface d'administration
    site_name: 'DevMag Admin'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: false
    design:
        # Ces lignes sont utiles pour CKEditor
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        # Ces lignes définiront notre menu
        menu:
            - { label: 'Articles' }
            - { entity: 'Articles', label: 'Articles', icon: 'book' }
            - { entity: 'Categories', label: 'Catégories', icon: 'tag' }
            - { entity: 'MotsCles', label: 'Mots Clés', icon: 'tag' }
            - { entity: 'Commentaires', label: 'Commentaires', icon: 'tag'}
            - { label: 'Utilisateurs' }
            - { entity: 'Users', label: 'Utilisateurs', icon: 'user' }
    formats:
        # Ici on définit le format des dates
        datetime: 'd/m/Y à H:i'
    entities:
        Articles:
            # Correspond au fichier Articles.php
            class: App\Entity\Articles
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - titre
                    - vip
                    - isFormation
                    # Le champ ci-dessous affichera l'image de l'article
                    - { property: 'featured_image', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
                    - { property: 'created_at', label: 'Créé' }
                    # Les catégories et les mots-clé sont listés ci-dessous
                    - { property: 'categories', label: 'Catégories', type: 'array'}
                    - { property: 'motsCles', label: 'Mots-Clés', type: 'array'}
                    - view
                    - likes
                    - published

                sort: ['created_at', 'desc']
            # On définit ci-dessous le contenu du formulaire d'ajout ou modification d'article
            form:
                fields:
                    - titre
                    - overview
                    - preview
                    - vip
                    - isFormation
                    # Affichage de l'éditeur Wysiwyg
                    - { property: 'contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    # Affichage du champ d'ajout d'image
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - users
                    # Les catégories et mots-clés peuvent s'afficher avec une sélection multiple
                    - { property: 'categories', label: 'Catégories', type: 'entity', type_options: { class: 'App\Entity\Categories', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}
                    - { property: 'motsCles', label: 'Mots Clés', type: 'entity', type_options: { class: 'App\Entity\MotsCles', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}
                    - { property: 'prev', label: 'Previous'}
                    - { property: 'next', label: 'Next'}
                    - published
        Users:
            class: App\Entity\Users
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - nom
                    - email
                    - membership_contract
                    - { property: 'roles', label: 'Rôles', type: json_array}
                    - activation_token
            form:
                fields:
                    - nom
                    - email
                    - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER','Editeur':'ROLE_EDITOR', 'Administrateur':'ROLE_ADMIN'}}}
                    - membership_contract
        Categories:
            class: App\Entity\Categories
            label: 'Catégorie'
            list:
                fields:
                    - id
                    - nom
            form:
                fields:
                    - nom
        MotsCles:
            class: App\Entity\MotsCles
            label: 'Mots clés'
            list:
                fields:
                    - id
                    - mot_cle
            form:
                fields:
                    - mot_cle
        Commentaires:
            class: App\Entity\Commentaires
            label: 'Commentaires'
            list:
                fields:
                    - id
                    - {property: 'articles', label: 'Articles'}
                    - pseudo
                    - email
                    - contenu
                    - actif
                    - created_at
                    
          